// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClgEv-NvPfDL1AKlS8H_XXVPuMc5xwaxs',
    appId: '1:605621175196:web:5b495cfbd03aefe559be59',
    messagingSenderId: '605621175196',
    projectId: 'mks-trading-buddy',
    authDomain: 'mks-trading-buddy.firebaseapp.com',
    storageBucket: 'mks-trading-buddy.firebasestorage.app',
    measurementId: 'G-61WW2BREGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_HSEqZia209k2AiyP3Z0ookstBBOfIE',
    appId: '1:605621175196:android:abc081ba604b8d8959be59',
    messagingSenderId: '605621175196',
    projectId: 'mks-trading-buddy',
    storageBucket: 'mks-trading-buddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlyiS-iU_RPXkrhW2wm_x6kUoPobxllk',
    appId: '1:605621175196:ios:14480076a0872cc659be59',
    messagingSenderId: '605621175196',
    projectId: 'mks-trading-buddy',
    storageBucket: 'mks-trading-buddy.firebasestorage.app',
    iosBundleId: 'com.example.mksTask2Tradingbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlyiS-iU_RPXkrhW2wm_x6kUoPobxllk',
    appId: '1:605621175196:ios:14480076a0872cc659be59',
    messagingSenderId: '605621175196',
    projectId: 'mks-trading-buddy',
    storageBucket: 'mks-trading-buddy.firebasestorage.app',
    iosBundleId: 'com.example.mksTask2Tradingbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClgEv-NvPfDL1AKlS8H_XXVPuMc5xwaxs',
    appId: '1:605621175196:web:076f22a1cda9904d59be59',
    messagingSenderId: '605621175196',
    projectId: 'mks-trading-buddy',
    authDomain: 'mks-trading-buddy.firebaseapp.com',
    storageBucket: 'mks-trading-buddy.firebasestorage.app',
    measurementId: 'G-PDV35RM8XC',
  );
}
